# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from prbt_hardware_support/BrakeTestErrorCodes.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BrakeTestErrorCodes(genpy.Message):
  _md5sum = "3d94689e95ce8a25b9e6555b0af70579"
  _type = "prbt_hardware_support/BrakeTestErrorCodes"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#
# Copyright (c) 2019 Pilz GmbH & Co. KG
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

int8 value

# values of CANopen object brake_test_status, see
# https://www.pilz.com/download/open/PRBT_6_Operat_Manual_1004685-EN-02.pdf (p.100)
int8 STATUS_UNKNOWN = 0
int8 STATUS_PERFORMING = 1
int8 STATUS_SUCCESS = 2
int8 STATUS_NO_SUCCESS = 3
int8 STATUS_NO_CONTROL = 4

# service call failures
int8 TRIGGER_BRAKETEST_SERVICE_FAILURE = 50
int8 GET_NODE_NAMES_FAILURE  = 51
int8 GET_DURATION_FAILURE = 52
int8 GET_STATUS_FAILURE = 53
int8 START_BRAKE_TEST_FAILURE = 54

# other reasons for blocking the execution of brake tests
int8 BRAKETEST_ALREADY_EXECUTING = 70
int8 ROBOT_MOTION_DETECTED = 71

# other
int8 FAILURE = 99
"""
  # Pseudo-constants
  STATUS_UNKNOWN = 0
  STATUS_PERFORMING = 1
  STATUS_SUCCESS = 2
  STATUS_NO_SUCCESS = 3
  STATUS_NO_CONTROL = 4
  TRIGGER_BRAKETEST_SERVICE_FAILURE = 50
  GET_NODE_NAMES_FAILURE = 51
  GET_DURATION_FAILURE = 52
  GET_STATUS_FAILURE = 53
  START_BRAKE_TEST_FAILURE = 54
  BRAKETEST_ALREADY_EXECUTING = 70
  ROBOT_MOTION_DETECTED = 71
  FAILURE = 99

  __slots__ = ['value']
  _slot_types = ['int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BrakeTestErrorCodes, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.value is None:
        self.value = 0
    else:
      self.value = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.value
      buff.write(_get_struct_b().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.value,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.value
      buff.write(_get_struct_b().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.value,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
