// Generated by gencpp from file tester_package/GenerateAnglesResponse.msg
// DO NOT EDIT!


#ifndef TESTER_PACKAGE_MESSAGE_GENERATEANGLESRESPONSE_H
#define TESTER_PACKAGE_MESSAGE_GENERATEANGLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tester_package
{
template <class ContainerAllocator>
struct GenerateAnglesResponse_
{
  typedef GenerateAnglesResponse_<ContainerAllocator> Type;

  GenerateAnglesResponse_()
    : angle(0.0)  {
    }
  GenerateAnglesResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateAnglesResponse_

typedef ::tester_package::GenerateAnglesResponse_<std::allocator<void> > GenerateAnglesResponse;

typedef boost::shared_ptr< ::tester_package::GenerateAnglesResponse > GenerateAnglesResponsePtr;
typedef boost::shared_ptr< ::tester_package::GenerateAnglesResponse const> GenerateAnglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tester_package::GenerateAnglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tester_package::GenerateAnglesResponse_<ContainerAllocator1> & lhs, const ::tester_package::GenerateAnglesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tester_package::GenerateAnglesResponse_<ContainerAllocator1> & lhs, const ::tester_package::GenerateAnglesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tester_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::tester_package::GenerateAnglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tester_package/GenerateAnglesResponse";
  }

  static const char* value(const ::tester_package::GenerateAnglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
;
  }

  static const char* value(const ::tester_package::GenerateAnglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateAnglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tester_package::GenerateAnglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tester_package::GenerateAnglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTER_PACKAGE_MESSAGE_GENERATEANGLESRESPONSE_H
