// Generated by gencpp from file tester_package/GenerateAngles.msg
// DO NOT EDIT!


#ifndef TESTER_PACKAGE_MESSAGE_GENERATEANGLES_H
#define TESTER_PACKAGE_MESSAGE_GENERATEANGLES_H

#include <ros/service_traits.h>


#include <tester_package/GenerateAnglesRequest.h>
#include <tester_package/GenerateAnglesResponse.h>


namespace tester_package
{

struct GenerateAngles
{

typedef GenerateAnglesRequest Request;
typedef GenerateAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateAngles
} // namespace tester_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tester_package::GenerateAngles > {
  static const char* value()
  {
    return "ce1f27368366dc4003cc92427b732647";
  }

  static const char* value(const ::tester_package::GenerateAngles&) { return value(); }
};

template<>
struct DataType< ::tester_package::GenerateAngles > {
  static const char* value()
  {
    return "tester_package/GenerateAngles";
  }

  static const char* value(const ::tester_package::GenerateAngles&) { return value(); }
};


// service_traits::MD5Sum< ::tester_package::GenerateAnglesRequest> should match
// service_traits::MD5Sum< ::tester_package::GenerateAngles >
template<>
struct MD5Sum< ::tester_package::GenerateAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tester_package::GenerateAngles >::value();
  }
  static const char* value(const ::tester_package::GenerateAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tester_package::GenerateAnglesRequest> should match
// service_traits::DataType< ::tester_package::GenerateAngles >
template<>
struct DataType< ::tester_package::GenerateAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::tester_package::GenerateAngles >::value();
  }
  static const char* value(const ::tester_package::GenerateAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tester_package::GenerateAnglesResponse> should match
// service_traits::MD5Sum< ::tester_package::GenerateAngles >
template<>
struct MD5Sum< ::tester_package::GenerateAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tester_package::GenerateAngles >::value();
  }
  static const char* value(const ::tester_package::GenerateAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tester_package::GenerateAnglesResponse> should match
// service_traits::DataType< ::tester_package::GenerateAngles >
template<>
struct DataType< ::tester_package::GenerateAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::tester_package::GenerateAngles >::value();
  }
  static const char* value(const ::tester_package::GenerateAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTER_PACKAGE_MESSAGE_GENERATEANGLES_H
