// Generated by gencpp from file prbt_hardware_support/BrakeTestResponse.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTRESPONSE_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prbt_hardware_support/BrakeTestErrorCodes.h>

namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct BrakeTestResponse_
{
  typedef BrakeTestResponse_<ContainerAllocator> Type;

  BrakeTestResponse_()
    : success(false)
    , error_code()
    , error_msg()  {
    }
  BrakeTestResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(_alloc)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator>  _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;





  typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeTestResponse_

typedef ::prbt_hardware_support::BrakeTestResponse_<std::allocator<void> > BrakeTestResponse;

typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestResponse > BrakeTestResponsePtr;
typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestResponse const> BrakeTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.error_msg == rhs.error_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8aa3acf608ed7e76565a588499702b4f";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8aa3acf608ed7e76ULL;
  static const uint64_t static_value2 = 0x565a588499702b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/BrakeTestResponse";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"# Number representing failure of the brake test\n"
"BrakeTestErrorCodes error_code\n"
"\n"
"# Contains message explaining failure of the brake test execution\n"
"string error_msg\n"
"\n"
"\n"
"================================================================================\n"
"MSG: prbt_hardware_support/BrakeTestErrorCodes\n"
"#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"int8 value\n"
"\n"
"# values of CANopen object brake_test_status, see\n"
"# https://www.pilz.com/download/open/PRBT_6_Operat_Manual_1004685-EN-02.pdf (p.100)\n"
"int8 STATUS_UNKNOWN = 0\n"
"int8 STATUS_PERFORMING = 1\n"
"int8 STATUS_SUCCESS = 2\n"
"int8 STATUS_NO_SUCCESS = 3\n"
"int8 STATUS_NO_CONTROL = 4\n"
"\n"
"# service call failures\n"
"int8 TRIGGER_BRAKETEST_SERVICE_FAILURE = 50\n"
"int8 GET_NODE_NAMES_FAILURE  = 51\n"
"int8 GET_DURATION_FAILURE = 52\n"
"int8 GET_STATUS_FAILURE = 53\n"
"int8 START_BRAKE_TEST_FAILURE = 54\n"
"\n"
"# other reasons for blocking the execution of brake tests\n"
"int8 BRAKETEST_ALREADY_EXECUTING = 70\n"
"int8 ROBOT_MOTION_DETECTED = 71\n"
"\n"
"# other\n"
"int8 FAILURE = 99\n"
;
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::BrakeTestResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    s << std::endl;
    Printer< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >::stream(s, indent + "  ", v.error_code);
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTRESPONSE_H
