// Generated by gencpp from file prbt_hardware_support/BrakeTest.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETEST_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETEST_H

#include <ros/service_traits.h>


#include <prbt_hardware_support/BrakeTestRequest.h>
#include <prbt_hardware_support/BrakeTestResponse.h>


namespace prbt_hardware_support
{

struct BrakeTest
{

typedef BrakeTestRequest Request;
typedef BrakeTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BrakeTest
} // namespace prbt_hardware_support


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prbt_hardware_support::BrakeTest > {
  static const char* value()
  {
    return "8aa3acf608ed7e76565a588499702b4f";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTest&) { return value(); }
};

template<>
struct DataType< ::prbt_hardware_support::BrakeTest > {
  static const char* value()
  {
    return "prbt_hardware_support/BrakeTest";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTest&) { return value(); }
};


// service_traits::MD5Sum< ::prbt_hardware_support::BrakeTestRequest> should match
// service_traits::MD5Sum< ::prbt_hardware_support::BrakeTest >
template<>
struct MD5Sum< ::prbt_hardware_support::BrakeTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prbt_hardware_support::BrakeTest >::value();
  }
  static const char* value(const ::prbt_hardware_support::BrakeTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prbt_hardware_support::BrakeTestRequest> should match
// service_traits::DataType< ::prbt_hardware_support::BrakeTest >
template<>
struct DataType< ::prbt_hardware_support::BrakeTestRequest>
{
  static const char* value()
  {
    return DataType< ::prbt_hardware_support::BrakeTest >::value();
  }
  static const char* value(const ::prbt_hardware_support::BrakeTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prbt_hardware_support::BrakeTestResponse> should match
// service_traits::MD5Sum< ::prbt_hardware_support::BrakeTest >
template<>
struct MD5Sum< ::prbt_hardware_support::BrakeTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prbt_hardware_support::BrakeTest >::value();
  }
  static const char* value(const ::prbt_hardware_support::BrakeTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prbt_hardware_support::BrakeTestResponse> should match
// service_traits::DataType< ::prbt_hardware_support::BrakeTest >
template<>
struct DataType< ::prbt_hardware_support::BrakeTestResponse>
{
  static const char* value()
  {
    return DataType< ::prbt_hardware_support::BrakeTest >::value();
  }
  static const char* value(const ::prbt_hardware_support::BrakeTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETEST_H
