// Generated by gencpp from file prbt_hardware_support/BrakeTestErrorCodes.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTERRORCODES_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTERRORCODES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct BrakeTestErrorCodes_
{
  typedef BrakeTestErrorCodes_<ContainerAllocator> Type;

  BrakeTestErrorCodes_()
    : value(0)  {
    }
  BrakeTestErrorCodes_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATUS_UNKNOWN)
  #undef STATUS_UNKNOWN
#endif
#if defined(_WIN32) && defined(STATUS_PERFORMING)
  #undef STATUS_PERFORMING
#endif
#if defined(_WIN32) && defined(STATUS_SUCCESS)
  #undef STATUS_SUCCESS
#endif
#if defined(_WIN32) && defined(STATUS_NO_SUCCESS)
  #undef STATUS_NO_SUCCESS
#endif
#if defined(_WIN32) && defined(STATUS_NO_CONTROL)
  #undef STATUS_NO_CONTROL
#endif
#if defined(_WIN32) && defined(TRIGGER_BRAKETEST_SERVICE_FAILURE)
  #undef TRIGGER_BRAKETEST_SERVICE_FAILURE
#endif
#if defined(_WIN32) && defined(GET_NODE_NAMES_FAILURE)
  #undef GET_NODE_NAMES_FAILURE
#endif
#if defined(_WIN32) && defined(GET_DURATION_FAILURE)
  #undef GET_DURATION_FAILURE
#endif
#if defined(_WIN32) && defined(GET_STATUS_FAILURE)
  #undef GET_STATUS_FAILURE
#endif
#if defined(_WIN32) && defined(START_BRAKE_TEST_FAILURE)
  #undef START_BRAKE_TEST_FAILURE
#endif
#if defined(_WIN32) && defined(BRAKETEST_ALREADY_EXECUTING)
  #undef BRAKETEST_ALREADY_EXECUTING
#endif
#if defined(_WIN32) && defined(ROBOT_MOTION_DETECTED)
  #undef ROBOT_MOTION_DETECTED
#endif
#if defined(_WIN32) && defined(FAILURE)
  #undef FAILURE
#endif

  enum {
    STATUS_UNKNOWN = 0,
    STATUS_PERFORMING = 1,
    STATUS_SUCCESS = 2,
    STATUS_NO_SUCCESS = 3,
    STATUS_NO_CONTROL = 4,
    TRIGGER_BRAKETEST_SERVICE_FAILURE = 50,
    GET_NODE_NAMES_FAILURE = 51,
    GET_DURATION_FAILURE = 52,
    GET_STATUS_FAILURE = 53,
    START_BRAKE_TEST_FAILURE = 54,
    BRAKETEST_ALREADY_EXECUTING = 70,
    ROBOT_MOTION_DETECTED = 71,
    FAILURE = 99,
  };


  typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeTestErrorCodes_

typedef ::prbt_hardware_support::BrakeTestErrorCodes_<std::allocator<void> > BrakeTestErrorCodes;

typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestErrorCodes > BrakeTestErrorCodesPtr;
typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestErrorCodes const> BrakeTestErrorCodesConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d94689e95ce8a25b9e6555b0af70579";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d94689e95ce8a25ULL;
  static const uint64_t static_value2 = 0xb9e6555b0af70579ULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/BrakeTestErrorCodes";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"int8 value\n"
"\n"
"# values of CANopen object brake_test_status, see\n"
"# https://www.pilz.com/download/open/PRBT_6_Operat_Manual_1004685-EN-02.pdf (p.100)\n"
"int8 STATUS_UNKNOWN = 0\n"
"int8 STATUS_PERFORMING = 1\n"
"int8 STATUS_SUCCESS = 2\n"
"int8 STATUS_NO_SUCCESS = 3\n"
"int8 STATUS_NO_CONTROL = 4\n"
"\n"
"# service call failures\n"
"int8 TRIGGER_BRAKETEST_SERVICE_FAILURE = 50\n"
"int8 GET_NODE_NAMES_FAILURE  = 51\n"
"int8 GET_DURATION_FAILURE = 52\n"
"int8 GET_STATUS_FAILURE = 53\n"
"int8 START_BRAKE_TEST_FAILURE = 54\n"
"\n"
"# other reasons for blocking the execution of brake tests\n"
"int8 BRAKETEST_ALREADY_EXECUTING = 70\n"
"int8 ROBOT_MOTION_DETECTED = 71\n"
"\n"
"# other\n"
"int8 FAILURE = 99\n"
;
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeTestErrorCodes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::BrakeTestErrorCodes_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTERRORCODES_H
