// Generated by gencpp from file prbt_hardware_support/BrakeTestRequest.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTREQUEST_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct BrakeTestRequest_
{
  typedef BrakeTestRequest_<ContainerAllocator> Type;

  BrakeTestRequest_()
    {
    }
  BrakeTestRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeTestRequest_

typedef ::prbt_hardware_support::BrakeTestRequest_<std::allocator<void> > BrakeTestRequest;

typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestRequest > BrakeTestRequestPtr;
typedef boost::shared_ptr< ::prbt_hardware_support::BrakeTestRequest const> BrakeTestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/BrakeTestRequest";
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"\n"
;
  }

  static const char* value(const ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeTestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::prbt_hardware_support::BrakeTestRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_BRAKETESTREQUEST_H
