// Generated by gencpp from file prbt_hardware_support/ModbusMsgInStamped.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_MODBUSMSGINSTAMPED_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_MODBUSMSGINSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt16MultiArray.h>
#include <std_msgs/Bool.h>

namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct ModbusMsgInStamped_
{
  typedef ModbusMsgInStamped_<ContainerAllocator> Type;

  ModbusMsgInStamped_()
    : header()
    , holding_registers()
    , disconnect()  {
    }
  ModbusMsgInStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , holding_registers(_alloc)
    , disconnect(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt16MultiArray_<ContainerAllocator>  _holding_registers_type;
  _holding_registers_type holding_registers;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _disconnect_type;
  _disconnect_type disconnect;





  typedef boost::shared_ptr< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ModbusMsgInStamped_

typedef ::prbt_hardware_support::ModbusMsgInStamped_<std::allocator<void> > ModbusMsgInStamped;

typedef boost::shared_ptr< ::prbt_hardware_support::ModbusMsgInStamped > ModbusMsgInStampedPtr;
typedef boost::shared_ptr< ::prbt_hardware_support::ModbusMsgInStamped const> ModbusMsgInStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.holding_registers == rhs.holding_registers &&
    lhs.disconnect == rhs.disconnect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1023ba57fc2f9bcbdf47284c68c44a57";
  }

  static const char* value(const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1023ba57fc2f9bcbULL;
  static const uint64_t static_value2 = 0xdf47284c68c44a57ULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/ModbusMsgInStamped";
  }

  static const char* value(const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/UInt16MultiArray holding_registers\n"
"std_msgs/Bool disconnect\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint16[]            data        # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.holding_registers);
      stream.next(m.disconnect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModbusMsgInStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::ModbusMsgInStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "holding_registers: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.holding_registers);
    s << indent << "disconnect: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.disconnect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_MODBUSMSGINSTAMPED_H
