// Generated by gencpp from file prbt_hardware_support/ModbusRegisterBlock.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_MODBUSREGISTERBLOCK_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_MODBUSREGISTERBLOCK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct ModbusRegisterBlock_
{
  typedef ModbusRegisterBlock_<ContainerAllocator> Type;

  ModbusRegisterBlock_()
    : start_idx(0)
    , values()  {
    }
  ModbusRegisterBlock_(const ContainerAllocator& _alloc)
    : start_idx(0)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _start_idx_type;
  _start_idx_type start_idx;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> const> ConstPtr;

}; // struct ModbusRegisterBlock_

typedef ::prbt_hardware_support::ModbusRegisterBlock_<std::allocator<void> > ModbusRegisterBlock;

typedef boost::shared_ptr< ::prbt_hardware_support::ModbusRegisterBlock > ModbusRegisterBlockPtr;
typedef boost::shared_ptr< ::prbt_hardware_support::ModbusRegisterBlock const> ModbusRegisterBlockConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator2> & rhs)
{
  return lhs.start_idx == rhs.start_idx &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe195cfcfc87bb5e9602528590f29a5d";
  }

  static const char* value(const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe195cfcfc87bb5eULL;
  static const uint64_t static_value2 = 0x9602528590f29a5dULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/ModbusRegisterBlock";
  }

  static const char* value(const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"# Defines the start index of the Modbus register block. A block can consist\n"
"# of one or more registers.\n"
"uint16 start_idx\n"
"\n"
"# The values of the registers (in order).\n"
"uint16[] values\n"
;
  }

  static const char* value(const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_idx);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModbusRegisterBlock_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator>& v)
  {
    s << indent << "start_idx: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.start_idx);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_MODBUSREGISTERBLOCK_H
