// Generated by gencpp from file prbt_hardware_support/SendBrakeTestResultResponse.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULTRESPONSE_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct SendBrakeTestResultResponse_
{
  typedef SendBrakeTestResultResponse_<ContainerAllocator> Type;

  SendBrakeTestResultResponse_()
    : success(false)
    , error_msg()  {
    }
  SendBrakeTestResultResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;





  typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendBrakeTestResultResponse_

typedef ::prbt_hardware_support::SendBrakeTestResultResponse_<std::allocator<void> > SendBrakeTestResultResponse;

typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultResponse > SendBrakeTestResultResponsePtr;
typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultResponse const> SendBrakeTestResultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_msg == rhs.error_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d006c48be24db1173a071ca9af4c8179";
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd006c48be24db117ULL;
  static const uint64_t static_value2 = 0x3a071ca9af4c8179ULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/SendBrakeTestResultResponse";
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"# Contains message explaining failure\n"
"string error_msg\n"
"\n"
;
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendBrakeTestResultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::SendBrakeTestResultResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULTRESPONSE_H
