// Generated by gencpp from file prbt_hardware_support/SendBrakeTestResult.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULT_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULT_H

#include <ros/service_traits.h>


#include <prbt_hardware_support/SendBrakeTestResultRequest.h>
#include <prbt_hardware_support/SendBrakeTestResultResponse.h>


namespace prbt_hardware_support
{

struct SendBrakeTestResult
{

typedef SendBrakeTestResultRequest Request;
typedef SendBrakeTestResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendBrakeTestResult
} // namespace prbt_hardware_support


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prbt_hardware_support::SendBrakeTestResult > {
  static const char* value()
  {
    return "09607d640e74f69f95d6976e7e821498";
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResult&) { return value(); }
};

template<>
struct DataType< ::prbt_hardware_support::SendBrakeTestResult > {
  static const char* value()
  {
    return "prbt_hardware_support/SendBrakeTestResult";
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResult&) { return value(); }
};


// service_traits::MD5Sum< ::prbt_hardware_support::SendBrakeTestResultRequest> should match
// service_traits::MD5Sum< ::prbt_hardware_support::SendBrakeTestResult >
template<>
struct MD5Sum< ::prbt_hardware_support::SendBrakeTestResultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prbt_hardware_support::SendBrakeTestResult >::value();
  }
  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prbt_hardware_support::SendBrakeTestResultRequest> should match
// service_traits::DataType< ::prbt_hardware_support::SendBrakeTestResult >
template<>
struct DataType< ::prbt_hardware_support::SendBrakeTestResultRequest>
{
  static const char* value()
  {
    return DataType< ::prbt_hardware_support::SendBrakeTestResult >::value();
  }
  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prbt_hardware_support::SendBrakeTestResultResponse> should match
// service_traits::MD5Sum< ::prbt_hardware_support::SendBrakeTestResult >
template<>
struct MD5Sum< ::prbt_hardware_support::SendBrakeTestResultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prbt_hardware_support::SendBrakeTestResult >::value();
  }
  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prbt_hardware_support::SendBrakeTestResultResponse> should match
// service_traits::DataType< ::prbt_hardware_support::SendBrakeTestResult >
template<>
struct DataType< ::prbt_hardware_support::SendBrakeTestResultResponse>
{
  static const char* value()
  {
    return DataType< ::prbt_hardware_support::SendBrakeTestResult >::value();
  }
  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULT_H
