// Generated by gencpp from file prbt_hardware_support/SendBrakeTestResultRequest.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULTREQUEST_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct SendBrakeTestResultRequest_
{
  typedef SendBrakeTestResultRequest_<ContainerAllocator> Type;

  SendBrakeTestResultRequest_()
    : result(false)  {
    }
  SendBrakeTestResultRequest_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendBrakeTestResultRequest_

typedef ::prbt_hardware_support::SendBrakeTestResultRequest_<std::allocator<void> > SendBrakeTestResultRequest;

typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultRequest > SendBrakeTestResultRequestPtr;
typedef boost::shared_ptr< ::prbt_hardware_support::SendBrakeTestResultRequest const> SendBrakeTestResultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/SendBrakeTestResultRequest";
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"# Variable to state the result of the last brake test.\n"
"# TRUE <-> Brake test successful\n"
"# FALSE <-> Brake test failed\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendBrakeTestResultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::SendBrakeTestResultRequest_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_SENDBRAKETESTRESULTREQUEST_H
