// Generated by gencpp from file prbt_hardware_support/WriteModbusRegisterRequest.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTERREQUEST_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prbt_hardware_support/ModbusRegisterBlock.h>

namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct WriteModbusRegisterRequest_
{
  typedef WriteModbusRegisterRequest_<ContainerAllocator> Type;

  WriteModbusRegisterRequest_()
    : holding_register_block()  {
    }
  WriteModbusRegisterRequest_(const ContainerAllocator& _alloc)
    : holding_register_block(_alloc)  {
  (void)_alloc;
    }



   typedef  ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator>  _holding_register_block_type;
  _holding_register_block_type holding_register_block;





  typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteModbusRegisterRequest_

typedef ::prbt_hardware_support::WriteModbusRegisterRequest_<std::allocator<void> > WriteModbusRegisterRequest;

typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterRequest > WriteModbusRegisterRequestPtr;
typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterRequest const> WriteModbusRegisterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.holding_register_block == rhs.holding_register_block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0851f7933b92fdd8b26651e23a384c83";
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0851f7933b92fdd8ULL;
  static const uint64_t static_value2 = 0xb26651e23a384c83ULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/WriteModbusRegisterRequest";
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"ModbusRegisterBlock holding_register_block\n"
"\n"
"\n"
"================================================================================\n"
"MSG: prbt_hardware_support/ModbusRegisterBlock\n"
"#\n"
"# Copyright (c) 2019 Pilz GmbH & Co. KG\n"
"#\n"
"# This program is free software: you can redistribute it and/or modify\n"
"# it under the terms of the GNU Lesser General Public License as published by\n"
"# the Free Software Foundation, either version 3 of the License, or\n"
"# (at your option) any later version.\n"
"#\n"
"# This program is distributed in the hope that it will be useful,\n"
"# but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"# GNU Lesser General Public License for more details.\n"
"#\n"
"# You should have received a copy of the GNU Lesser General Public License\n"
"# along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
"\n"
"# Defines the start index of the Modbus register block. A block can consist\n"
"# of one or more registers.\n"
"uint16 start_idx\n"
"\n"
"# The values of the registers (in order).\n"
"uint16[] values\n"
;
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.holding_register_block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteModbusRegisterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::WriteModbusRegisterRequest_<ContainerAllocator>& v)
  {
    s << indent << "holding_register_block: ";
    s << std::endl;
    Printer< ::prbt_hardware_support::ModbusRegisterBlock_<ContainerAllocator> >::stream(s, indent + "  ", v.holding_register_block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTERREQUEST_H
