// Generated by gencpp from file prbt_hardware_support/WriteModbusRegisterResponse.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTERRESPONSE_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prbt_hardware_support
{
template <class ContainerAllocator>
struct WriteModbusRegisterResponse_
{
  typedef WriteModbusRegisterResponse_<ContainerAllocator> Type;

  WriteModbusRegisterResponse_()
    : success(false)  {
    }
  WriteModbusRegisterResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WriteModbusRegisterResponse_

typedef ::prbt_hardware_support::WriteModbusRegisterResponse_<std::allocator<void> > WriteModbusRegisterResponse;

typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterResponse > WriteModbusRegisterResponsePtr;
typedef boost::shared_ptr< ::prbt_hardware_support::WriteModbusRegisterResponse const> WriteModbusRegisterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator1> & lhs, const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prbt_hardware_support

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prbt_hardware_support/WriteModbusRegisterResponse";
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteModbusRegisterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prbt_hardware_support::WriteModbusRegisterResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTERRESPONSE_H
