// Generated by gencpp from file prbt_hardware_support/WriteModbusRegister.msg
// DO NOT EDIT!


#ifndef PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTER_H
#define PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTER_H

#include <ros/service_traits.h>


#include <prbt_hardware_support/WriteModbusRegisterRequest.h>
#include <prbt_hardware_support/WriteModbusRegisterResponse.h>


namespace prbt_hardware_support
{

struct WriteModbusRegister
{

typedef WriteModbusRegisterRequest Request;
typedef WriteModbusRegisterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteModbusRegister
} // namespace prbt_hardware_support


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prbt_hardware_support::WriteModbusRegister > {
  static const char* value()
  {
    return "02822f7d1076b1b9eb20913904f86345";
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegister&) { return value(); }
};

template<>
struct DataType< ::prbt_hardware_support::WriteModbusRegister > {
  static const char* value()
  {
    return "prbt_hardware_support/WriteModbusRegister";
  }

  static const char* value(const ::prbt_hardware_support::WriteModbusRegister&) { return value(); }
};


// service_traits::MD5Sum< ::prbt_hardware_support::WriteModbusRegisterRequest> should match
// service_traits::MD5Sum< ::prbt_hardware_support::WriteModbusRegister >
template<>
struct MD5Sum< ::prbt_hardware_support::WriteModbusRegisterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prbt_hardware_support::WriteModbusRegister >::value();
  }
  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prbt_hardware_support::WriteModbusRegisterRequest> should match
// service_traits::DataType< ::prbt_hardware_support::WriteModbusRegister >
template<>
struct DataType< ::prbt_hardware_support::WriteModbusRegisterRequest>
{
  static const char* value()
  {
    return DataType< ::prbt_hardware_support::WriteModbusRegister >::value();
  }
  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prbt_hardware_support::WriteModbusRegisterResponse> should match
// service_traits::MD5Sum< ::prbt_hardware_support::WriteModbusRegister >
template<>
struct MD5Sum< ::prbt_hardware_support::WriteModbusRegisterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prbt_hardware_support::WriteModbusRegister >::value();
  }
  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prbt_hardware_support::WriteModbusRegisterResponse> should match
// service_traits::DataType< ::prbt_hardware_support::WriteModbusRegister >
template<>
struct DataType< ::prbt_hardware_support::WriteModbusRegisterResponse>
{
  static const char* value()
  {
    return DataType< ::prbt_hardware_support::WriteModbusRegister >::value();
  }
  static const char* value(const ::prbt_hardware_support::WriteModbusRegisterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRBT_HARDWARE_SUPPORT_MESSAGE_WRITEMODBUSREGISTER_H
